nav:
  - 首页：README.md
  - 用户指南：
    - 使用指南：usage/README.md
    - 快速入门：
      - getting_started/quickstart.md
      - getting_started/installation
      - 示例：examples
    - 通用：
      - usage/v1_guide.md
      - usage/*
    - 推理与服务：
      - serving/offline_inference.md
      - 在线服务：serving/online_serving
      - serving/*
      - serving/integrations
    - 部署：
      - deployment/*
      - deployment/frameworks
      - deployment/integrations
    - 训练：training
    - 配置：
      - configuration/*
      - TPU：https://docs.vllm.ai/projects/tpu/en/latest/
    - 模型：
      - models/supported_models.md
      - models/generative_models.md
      - 池化模型：models/pooling_models
      - models/extensions
      - 硬件支持模型：
        - models/hardware_supported_models/*
        - TPU：https://docs.vllm.ai/projects/tpu/en/latest/recommended_models_features/
    - 功能：features
  - 开发者指南：
    - contributing/README.md
    - 通用：
      - glob: contributing/*
        flatten_single_child_sections: true
    - 模型实现：
      - contributing/model/README.md
      - contributing/model/basic.md
      - contributing/model/registration.md
      - contributing/model/tests.md
      - contributing/model/multimodal.md
      - contributing/model/transcription.md
    - CI：contributing/ci
    - 设计文档：
      - 插件：
        - design/*plugin*.md
      - design/*
  - 基准测试：
      - benchmarking/README.md
      - benchmarking/cli.md
      - benchmarking/sweeps.md
      - benchmarking/dashboard.md
  - API 参考：
    - api/README.md
    - api/vllm
  - CLI 参考：
    - cli/README.md
    - vllm：cli
  - 社区：
    - community/*
    - 治理：governance
    - 博客：https://blog.vllm.ai
    - 论坛：https://discuss.vllm.ai
    - Slack：https://slack.vllm.ai
